
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rkdwlss2/msa-configurations
#          username: rkdwlss2
#          password: #??
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health
#  profiles:
#    active: native
#
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file://${user.home}/Downloads/configFiles
