
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rkdwlss2/msa-configurations
#          username: rkdwlss2
#          password: #??
#  profiles:
#    active: native
#
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file://${user.home}/Downloads/configFiles
